version: '3.8'

services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: hr_dashboard
      POSTGRES_USER: hr_user
      POSTGRES_PASSWORD: "BcF6$w&O&RLVJqpsT2gx62JK6Ppxe#jc"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U hr_user -d hr_dashboard"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    command: gunicorn hr_backend.wsgi:application --bind 0.0.0.0:8000 --workers 2
    network_mode: "host"
    environment:
      - DEBUG=False
      - SECRET_KEY="+=JhLk!GJHEbRpb9t&$Q6&!w_=29QrML9%9qNc@4^981K=bc5p"
      - DB_NAME=hr_dashboard
      - DB_USER=hr_user
      - DB_PASSWORD="BcF6$w&O&RLVJqpsT2gx62JK6Ppxe#jc"
      - DB_HOST=localhost
      - DB_PORT=5432
      - ALLOWED_HOSTS=localhost,127.0.0.1,37.27.15.92,backend,hr-dashboard.novadev-edge.io
      - CORS_ALLOWED_ORIGINS=http://localhost:4200,http://127.0.0.1:4200,http://37.27.15.92,https://hr-dashboard.novadev-edge.io
      - EMAIL_HOST=mail.your-server.de
      - EMAIL_PORT=587
      - EMAIL_USE_TLS=True
      - EMAIL_HOST_USER=hr@novadev-edge.io
      - EMAIL_HOST_PASSWORD="6hM34Zr8D74Ry1j6"
      - DEFAULT_FROM_EMAIL=hr@novadev-edge.io

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - backend
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge