# ⚠️ WARNING: Change all passwords and secrets before deploying to production!
# - POSTGRES_PASSWORD
# - SECRET_KEY
# - Admin password (in setup.sh)

version: '3.8'

services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: hr_dashboard
      POSTGRES_USER: hr_user
      POSTGRES_PASSWORD: PostgreSQL_Password_2025_Secure!
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U hr_user -d hr_dashboard"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    command: gunicorn hr_backend.wsgi:application --bind 0.0.0.0:8000 --workers 2
    environment:
      - DEBUG=False
      - SECRET_KEY=hr-dashboard-production-secret-key-change-in-production-2025
      - DB_NAME=hr_dashboard
      - DB_USER=hr_user
      - DB_PASSWORD=PostgreSQL_Password_2025_Secure!
      - DB_HOST=db
      - DB_PORT=5432
      - ALLOWED_HOSTS=localhost,127.0.0.1,37.27.15.92,backend
      - CORS_ALLOWED_ORIGINS=http://localhost:4200,http://127.0.0.1:4200,http://37.27.15.92
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network

  frontend:
  build:
    context: .
    dockerfile: Dockerfile.frontend
  ports:
    - "80:80"
    - "443:443"
  volumes:
    - /etc/letsencrypt:/etc/letsencrypt:ro
  depends_on:
    - backend
  networks:
    - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge